title: GitHub Pages
author: ebassett
email: ebassett@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Site description. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
github_username:  ebassett

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
